
export const competitiveItems = [
  { id: 'sticky-barb', name: 'Sticky Barb', category: 'Items', description: 'Each turn, holder loses 1/8 max HP. An attacker making contact can receive it.' },
  { id: 'air-balloon', name: 'Air Balloon', category: 'Popular items', description: 'Holder is immune to Ground-type attacks. Pops when holder is hit.' },
  { id: 'assault-vest', name: 'Assault Vest', category: 'Popular items', description: "Holder's Sp. Def is 1.5x, but it can only select damaging moves." },
  { id: 'choice-band', name: 'Choice Band', category: 'Popular items', description: "Holder's Attack is 1.5x, but it can only select the first move it executes." },
  { id: 'choice-scarf', name: 'Choice Scarf', category: 'Popular items', description: "Holder's Speed is 1.5x, but it can only select the first move it executes." },
  { id: 'choice-specs', name: 'Choice Specs', category: 'Popular items', description: "Holder's Sp. Atk is 1.5x, but it can only select the first move it executes." },
  { id: 'expert-belt', name: 'Expert Belt', category: 'Popular items', description: "Holder's attacks that are super effective against the target do 1.2x damage." },
  { id: 'focus-sash', name: 'Focus Sash', category: 'Popular items', description: "If holder's HP is full, will survive an attack that would KO it with 1 HP. Single use." },
  { id: 'heavy-duty-boots', name: 'Heavy-Duty Boots', category: 'Popular items', description: 'When switching in, the holder is unaffected by hazards on its side of the field.' },
  { id: 'leftovers', name: 'Leftovers', category: 'Popular items', description: 'At the end of every turn, holder restores 1/16 of its max HP.' },
  { id: 'life-orb', name: 'Life Orb', category: 'Popular items', description: "Holder's attacks do 1.3x damage, and it loses 1/10 its max HP after the attack." },
  { id: 'loaded-dice', name: 'Loaded Dice', category: 'Popular items', description: "Holder's moves that hit 2-5 times hit 4-5 times; Population Bomb hits 4-10 times." },
  { id: 'mental-herb', name: 'Mental Herb', category: 'Popular items', description: 'Cures holder of Attract, Disable, Encore, Heal Block, Taunt, Torment. Single use.' },
  { id: 'power-herb', name: 'Power Herb', category: 'Popular items', description: 'Holder\'s two-turn moves complete in one turn (except Sky Drop). Single use.' },
  { id: 'rocky-helmet', name: 'Rocky Helmet', category: 'Popular items', description: 'If holder is hit by a contact move, the attacker loses 1/6 of its max HP.' },
  { id: 'salac-berry', name: 'Salac Berry', category: 'Popular items', description: "Raises holder's Speed by 1 stage when at 1/4 max HP or less. Single use." },
  { id: 'ability-shield', name: 'Ability Shield', category: 'Items', description: "Holder's Ability cannot be changed, suppressed, or ignored by any effect." },
  { id: 'absorb-bulb', name: 'Absorb Bulb', category: 'Items', description: "Raises holder's Sp. Atk by 1 stage if hit by a Water-type attack. Single use." },
  { id: 'adrenaline-orb', name: 'Adrenaline Orb', category: 'Items', description: 'Raises holder\'s Speed by 1 stage if it gets affected by Intimidate. Single use.' },
  { id: 'aguav-berry', name: 'Aguav Berry', category: 'Items', description: 'Restores 1/3 max HP at 1/4 max HP or less; confuses if -SpD Nature. Single use.' },
  { id: 'apicot-berry', name: 'Apicot Berry', category: 'Items', description: "Raises holder's Sp. Def by 1 stage when at 1/4 max HP or less. Single use." },
  { id: 'babiri-berry', name: 'Babiri Berry', category: 'Items', description: 'Halves damage taken from a supereffective Steel-type attack. Single use.' },
  { id: 'black-belt', name: 'Black Belt', category: 'Items', description: "Holder's Fighting-type attacks have 1.2x power." },
  { id: 'black-glasses', name: 'Black Glasses', category: 'Items', description: "Holder's Dark-type attacks have 1.2x power." },
  { id: 'black-sludge', name: 'Black Sludge', category: 'Items', description: 'Each turn, if holder is a Poison type, restores 1/16 max HP; loses 1/8 if not.' },
  { id: 'blunder-policy', name: 'Blunder Policy', category: 'Items', description: "If the holder misses due to accuracy, its Speed is raised by 2 stages. Single use." },
  { id: 'booster-energy', name: 'Booster Energy', category: 'Items', description: 'Activates the Protosynthesis or Quark Drive Abilities. Single use.' },
  { id: 'bright-powder', name: 'Bright Powder', category: 'Items', description: 'The accuracy of attacks against the holder is 0.9x.' },
  { id: 'cell-battery', name: 'Cell Battery', category: 'Items', description: "Raises holder's Attack by 1 if hit by an Electric-type attack. Single use." },
  { id: 'charcoal', name: 'Charcoal', category: 'Items', description: "Holder's Fire-type attacks have 1.2x power." },
  { id: 'charti-berry', name: 'Charti Berry', category: 'Items', description: 'Halves damage taken from a supereffective Rock-type attack. Single use.' },
  { id: 'chesto-berry', name: 'Chesto Berry', category: 'Items', description: 'Holder wakes up if it is asleep. Single use.' },
  { id: 'chilan-berry', name: 'Chilan Berry', category: 'Items', description: 'Halves damage taken from a Normal-type attack. Single use.' },
  { id: 'chople-berry', name: 'Chople Berry', category: 'Items', description: 'Halves damage taken from a supereffective Fighting-type attack. Single use.' },
  { id: 'clear-amulet', name: 'Clear Amulet', category: 'Items', description: "Prevents other Pokemon from lowering the holder's stat stages." },
  { id: 'coba-berry', name: 'Coba Berry', category: 'Items', description: 'Halves damage taken from a supereffective Flying-type attack. Single use.' },
  { id: 'colbur-berry', name: 'Colbur Berry', category: 'Items', description: 'Halves damage taken from a supereffective Dark-type attack. Single use.' },
  { id: 'covert-cloak', name: 'Covert Cloak', category: 'Items', description: "Holder is not affected by the secondary effect of another Pokemon's attack." },
  { id: 'custap-berry', name: 'Custap Berry', category: 'Items', description: 'Holder moves first in its priority bracket when at 1/4 max HP or less. Single use.' },
  { id: 'damp-rock', name: 'Damp Rock', category: 'Items', description: "Holder's use of Rain Dance lasts 8 turns instead of 5." },
  { id: 'draco-plate', name: 'Draco Plate', category: 'Items', description: "Holder's Dragon-type attacks have 1.2x power. Judgment is Dragon type." },
  { id: 'dragon-fang', name: 'Dragon Fang', category: 'Items', description: "Holder's Dragon-type attacks have 1.2x power." },
  { id: 'dread-plate', name: 'Dread Plate', category: 'Items', description: "Holder's Dark-type attacks have 1.2x power. Judgment is Dark type." },
  { id: 'earth-plate', name: 'Earth Plate', category: 'Items', description: "Holder's Ground-type attacks have 1.2x power. Judgment is Ground type." },
  { id: 'eject-button', name: 'Eject Button', category: 'Items', description: 'If holder survives a hit, it immediately switches out to a chosen ally. Single use.' },
  { id: 'eject-pack', name: 'Eject Pack', category: 'Items', description: "If the holder's stat stages are lowered, it switches to a chosen ally. Single use." },
  { id: 'electric-seed', name: 'Electric Seed', category: 'Items', description: "If the terrain is Electric Terrain, raises holder's Defense by 1 stage. Single use." },
  { id: 'eviolite', name: 'Eviolite', category: 'Items', description: "If holder's species can evolve, its Defense and Sp. Def are 1.5x." },
  { id: 'fairy-feather', name: 'Fairy Feather', category: 'Items', description: "Holder's Fairy-type attacks have 1.2x power." },
  { id: 'figy-berry', name: 'Figy Berry', category: 'Items', description: 'Restores 1/3 max HP at 1/4 max HP or less; confuses if -Atk Nature. Single use.' },
  { id: 'fist-plate', name: 'Fist Plate', category: 'Items', description: "Holder's Fighting-type attacks have 1.2x power. Judgment is Fighting type." },
  { id: 'flame-orb', name: 'Flame Orb', category: 'Items', description: 'At the end of every turn, this item attempts to burn the holder.' },
  { id: 'flame-plate', name: 'Flame Plate', category: 'Items', description: "Holder's Fire-type attacks have 1.2x power. Judgment is Fire type." },
  { id: 'ganlon-berry', name: 'Ganlon Berry', category: 'Items', description: "Raises holder's Defense by 1 stage when at 1/4 max HP or less. Single use." },
  { id: 'grassy-seed', name: 'Grassy Seed', category: 'Items', description: "If the terrain is Grassy Terrain, raises holder's Defense by 1 stage. Single use." },
  { id: 'grepa-berry', name: 'Grepa Berry', category: 'Items', description: 'Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.' },
  { id: 'grip-claw', name: 'Grip Claw', category: 'Items', description: "Holder's partial-trapping moves always last 7 turns." },
  { id: 'haban-berry', name: 'Haban Berry', category: 'Items', description: 'Halves damage taken from a supereffective Dragon-type attack. Single use.' },
  { id: 'hard-stone', name: 'Hard Stone', category: 'Items', description: "Holder's Rock-type attacks have 1.2x power." },
  { id: 'heat-rock', name: 'Heat Rock', category: 'Items', description: "Holder's use of Sunny Day lasts 8 turns instead of 5." },
  { id: 'iapapa-berry', name: 'Iapapa Berry', category: 'Items', description: 'Restores 1/3 max HP at 1/4 max HP or less; confuses if -Def Nature. Single use.' },
  { id: 'icicle-plate', name: 'Icicle Plate', category: 'Items', description: "Holder's Ice-type attacks have 1.2x power. Judgment is Ice type." },
  { id: 'icy-rock', name: 'Icy Rock', category: 'Items', description: "Holder's use of Snowscape lasts 8 turns instead of 5." },
  { id: 'insect-plate', name: 'Insect Plate', category: 'Items', description: "Holder's Bug-type attacks have 1.2x power. Judgment is Bug type." },
  { id: 'iron-plate', name: 'Iron Plate', category: 'Items', description: "Holder's Steel-type attacks have 1.2x power. Judgment is Steel type." },
  { id: 'kasib-berry', name: 'Kasib Berry', category: 'Items', description: 'Halves damage taken from a supereffective Ghost-type attack. Single use.' },
  { id: 'kebia-berry', name: 'Kebia Berry', category: 'Items', description: 'Halves damage taken from a supereffective Poison-type attack. Single use.' },
  { id: 'kee-berry', name: 'Kee Berry', category: 'Items', description: 'Raises holder\'s Defense by 1 stage after it is hit by a physical attack. Single use.' },
  { id: 'kelpsy-berry', name: 'Kelpsy Berry', category: 'Items', description: 'Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.' },
  { id: 'kings-rock', name: 'King\'s Rock', category: 'Items', description: "Holder's attacks without a chance to flinch gain a 10% chance to flinch." },
  { id: 'lagging-tail', name: 'Lagging Tail', category: 'Items', description: 'Holder moves last in its priority bracket.' },
  { id: 'lansat-berry', name: 'Lansat Berry', category: 'Items', description: 'Holder gains the Focus Energy effect when at 1/4 max HP or less. Single use.' },
  { id: 'leppa-berry', name: 'Leppa Berry', category: 'Items', description: "Restores 10 PP to the first of the holder's moves to reach 0 PP. Single use." },
  { id: 'liechi-berry', name: 'Liechi Berry', category: 'Items', description: "Raises holder's Attack by 1 stage when at 1/4 max HP or less. Single use." },
  { id: 'light-clay', name: 'Light Clay', category: 'Items', description: "Holder's use of Aurora Veil, Light Screen, or Reflect lasts 8 turns instead of 5." },
  { id: 'lum-berry', name: 'Lum Berry', category: 'Items', description: 'Holder cures itself if it has a non-volatile status or is confused. Single use.' },
  { id: 'luminous-moss', name: 'Luminous Moss', category: 'Items', description: "Raises holder's Sp. Def by 1 stage if hit by a Water-type attack. Single use." },
  { id: 'magnet', name: 'Magnet', category: 'Items', description: "Holder's Electric-type attacks have 1.2x power." },
  { id: 'mago-berry', name: 'Mago Berry', category: 'Items', description: 'Restores 1/3 max HP at 1/4 max HP or less; confuses if -Spe Nature. Single use.' },
  { id: 'maranga-berry', name: 'Maranga Berry', category: 'Items', description: "Raises holder's Sp. Def by 1 stage after it is hit by a special attack. Single use." },
  { id: 'meadow-plate', name: 'Meadow Plate', category: 'Items', description: "Holder's Grass-type attacks have 1.2x power. Judgment is Grass type." },
  { id: 'metal-coat', name: 'Metal Coat', category: 'Items', description: "Holder's Steel-type attacks have 1.2x power." },
  { id: 'metronome', name: 'Metronome', category: 'Items', description: 'Damage of moves used on consecutive turns is increased. Max 2x after 5 turns.' },
  { id: 'micle-berry', name: 'Micle Berry', category: 'Items', description: "Holder's next move has 1.2x accuracy when at 1/4 max HP or less. Single use." },
  { id: 'mind-plate', name: 'Mind Plate', category: 'Items', description: "Holder's Psychic-type attacks have 1.2x power. Judgment is Psychic type." },
  { id: 'miracle-seed', name: 'Miracle Seed', category: 'Items', description: "Holder's Grass-type attacks have 1.2x power." },
  { id: 'mirror-herb', name: 'Mirror Herb', category: 'Items', description: 'When an opposing Pokemon raises a stat stage, the holder copies it. Single use.' },
  { id: 'misty-seed', name: 'Misty Seed', category: 'Items', description: "If the terrain is Misty Terrain, raises holder's Sp. Def by 1 stage. Single use." },
  { id: 'muscle-band', name: 'Muscle Band', category: 'Items', description: "Holder's physical attacks have 1.1x power." },
  { id: 'mystic-water', name: 'Mystic Water', category: 'Items', description: "Holder's Water-type attacks have 1.2x power." },
  { id: 'never-melt-ice', name: 'Never-Melt Ice', category: 'Items', description: "Holder's Ice-type attacks have 1.2x power." },
  { id: 'normal-gem', name: 'Normal Gem', category: 'Items', description: "Holder's first successful Normal-type attack will have 1.3x power. Single use." },
  { id: 'occa-berry', name: 'Occa Berry', category: 'Items', description: 'Halves damage taken from a supereffective Fire-type attack. Single use.' },
  { id: 'passho-berry', name: 'Passho Berry', category: 'Items', description: 'Halves damage taken from a supereffective Water-type attack. Single use.' },
  { id: 'payapa-berry', name: 'Payapa Berry', category: 'Items', description: 'Halves damage taken from a supereffective Psychic-type attack. Single use.' },
  { id: 'petaya-berry', name: 'Petaya Berry', category: 'Items', description: "Raises holder's Sp. Atk by 1 stage when at 1/4 max HP or less. Single use." },
  { id: 'pixie-plate', name: 'Pixie Plate', category: 'Items', description: "Holder's Fairy-type attacks have 1.2x power. Judgment is Fairy type." },
  { id: 'poison-barb', name: 'Poison Barb', category: 'Items', description: "Holder's Poison-type attacks have 1.2x power." },
  { id: 'protective-pads', name: 'Protective Pads', category: 'Items', description: "Holder's moves are protected from adverse contact effects, except Pickpocket." },
  { id: 'psychic-seed', name: 'Psychic Seed', category: 'Items', description: "If the terrain is Psychic Terrain, raises holder's Sp. Def by 1 stage. Single use." },
  { id: 'punching-glove', name: 'Punching Glove', category: 'Items', description: 'Holder\'s punch-based attacks have 1.1x power and do not make contact.' },
  { id: 'quick-claw', name: 'Quick Claw', category: 'Items', description: 'Each turn, holder has a 20% chance to move first in its priority bracket.' },
  { id: 'razor-claw', name: 'Razor Claw', category: 'Items', description: "Holder's critical hit ratio is raised by 1 stage." },
  { id: 'razor-fang', name: 'Razor Fang', category: 'Items', description: "Holder's attacks without a chance to flinch gain a 10% chance to flinch." },
  { id: 'red-card', name: 'Red Card', category: 'Items', description: 'If holder survives a hit, attacker is forced to switch to a random ally. Single use.' },
  { id: 'rindo-berry', name: 'Rindo Berry', category: 'Items', description: 'Halves damage taken from a supereffective Grass-type attack. Single use.' },
  { id: 'room-service', name: 'Room Service', category: 'Items', description: "If Trick Room is active, the holder's Speed is lowered by 1 stage. Single use." },
  { id: 'roseli-berry', name: 'Roseli Berry', category: 'Items', description: 'Halves damage taken from a supereffective Fairy-type attack. Single use.' },
  { id: 'scope-lens', name: 'Scope Lens', category: 'Items', description: "Holder's critical hit ratio is raised by 1 stage." },
  { id: 'sharp-beak', name: 'Sharp Beak', category: 'Items', description: "Holder's Flying-type attacks have 1.2x power." },
  { id: 'shed-shell', name: 'Shed Shell', category: 'Items', description: 'Holder cannot be prevented from choosing to switch out by any effect.' },
  { id: 'shell-bell', name: 'Shell Bell', category: 'Items', description: 'After an attack, holder gains 1/8 of the damage in HP dealt to other Pokemon.' },
  { id: 'shuca-berry', name: 'Shuca Berry', category: 'Items', description: 'Halves damage taken from a supereffective Ground-type attack. Single use.' },
  { id: 'silk-scarf', name: 'Silk Scarf', category: 'Items', description: "Holder's Normal-type attacks have 1.2x power." },
  { id: 'silver-powder', name: 'Silver Powder', category: 'Items', description: "Holder's Bug-type attacks have 1.2x power." },
  { id: 'sitrus-berry', name: 'Sitrus Berry', category: 'Items', description: 'Restores 1/4 max HP when at 1/2 max HP or less. Single use.' },
  { id: 'sky-plate', name: 'Sky Plate', category: 'Items', description: "Holder's Flying-type attacks have 1.2x power. Judgment is Flying type." },
  { id: 'smooth-rock', name: 'Smooth Rock', category: 'Items', description: "Holder's use of Sandstorm lasts 8 turns instead of 5." },
  { id: 'snowball', name: 'Snowball', category: 'Items', description: "Raises holder's Attack by 1 if hit by an Ice-type attack. Single use." },
  { id: 'soft-sand', name: 'Soft Sand', category: 'Items', description: "Holder's Ground-type attacks have 1.2x power." },
  { id: 'spell-tag', name: 'Spell Tag', category: 'Items', description: "Holder's Ghost-type attacks have 1.2x power." },
  { id: 'splash-plate', name: 'Splash Plate', category: 'Items', description: "Holder's Water-type attacks have 1.2x power. Judgment is Water type." },
  { id: 'spooky-plate', name: 'Spooky Plate', category: 'Items', description: "Holder's Ghost-type attacks have 1.2x power. Judgment is Ghost type." },
  { id: 'starf-berry', name: 'Starf Berry', category: 'Items', description: 'Raises a random stat by 2 when at 1/4 max HP or less (not acc/eva). Single use.' },
  { id: 'stone-plate', name: 'Stone Plate', category: 'Items', description: "Holder's Rock-type attacks have 1.2x power. Judgment is Rock type." },
  { id: 'tanga-berry', name: 'Tanga Berry', category: 'Items', description: 'Halves damage taken from a supereffective Bug-type attack. Single use.' },
  { id: 'terrain-extender', name: 'Terrain Extender', category: 'Items', description: "Holder's use of Electric/Grassy/Misty/Psychic Terrain lasts 8 turns instead of 5." },
  { id: 'throat-spray', name: 'Throat Spray', category: 'Items', description: "Raises holder's Special Attack by 1 stage after it uses a sound move. Single use." },
  { id: 'toxic-orb', name: 'Toxic Orb', category: 'Items', description: 'At the end of every turn, this item attempts to badly poison the holder.' },
  { id: 'toxic-plate', name: 'Toxic Plate', category: 'Items', description: "Holder's Poison-type attacks have 1.2x power. Judgment is Poison type." },
  { id: 'twisted-spoon', name: 'Twisted Spoon', category: 'Items', description: "Holder's Psychic-type attacks have 1.2x power." },
  { id: 'utility-umbrella', name: 'Utility Umbrella', category: 'Items', description: 'The holder ignores rain- and sun-based effects.' },
  { id: 'wacan-berry', name: 'Wacan Berry', category: 'Items', 'description': 'Halves damage taken from a supereffective Electric-type attack. Single use.' },
  { id: 'white-herb', name: 'White Herb', category: 'Items', description: 'Restores all lowered stat stages to 0 when one is less than 0. Single use.' },
  { id: 'wide-lens', name: 'Wide Lens', category: 'Items', description: 'The accuracy of attacks by the holder is 1.1x.' },
  { id: 'wiki-berry', name: 'Wiki Berry', category: 'Items', description: 'Restores 1/3 max HP at 1/4 max HP or less; confuses if -SpA Nature. Single use.' },
  { id: 'wise-glasses', name: 'Wise Glasses', category: 'Items', description: "Holder's special attacks have 1.1x power." },
  { id: 'yache-berry', name: 'Yache Berry', category: 'Items', description: 'Halves damage taken from a supereffective Ice-type attack. Single use.' },
  { id: 'zap-plate', name: 'Zap Plate', category: 'Items', description: "Holder's Electric-type attacks have 1.2x power. Judgment is Electric type." },
  { id: 'zoom-lens', name: 'Zoom Lens', category: 'Items', description: 'The accuracy of attacks by the holder is 1.2x if it moves after its target.' },
  { id: 'adamant-crystal', name: 'Adamant Crystal', category: 'Pokémon-specific items', description: "If held by a Dialga, its Steel- and Dragon-type attacks have 1.2x power." },
  { id: 'adamant-orb', name: 'Adamant Orb', category: 'Pokémon-specific items', description: "If held by a Dialga, its Steel- and Dragon-type attacks have 1.2x power." },
  { id: 'cornerstone-mask', name: 'Cornerstone Mask', category: 'Pokémon-specific items', description: 'Ogerpon-Cornerstone: 1.2x power attacks; Terastallize to gain Embody Aspect.' },
  { id: 'griseous-core', name: 'Griseous Core', category: 'Pokémon-specific items', description: "If held by a Giratina, its Ghost- and Dragon-type attacks have 1.2x power." },
  { id: 'griseous-orb', name: 'Griseous Orb', category: 'Pokémon-specific items', description: "If held by a Giratina, its Ghost- and Dragon-type attacks have 1.2x power." },
  { id: 'hearthflame-mask', name: 'Hearthflame Mask', category: 'Pokémon-specific items', description: 'Ogerpon-Hearthflame: 1.2x power attacks; Terastallize to gain Embody Aspect.' },
  { id: 'light-ball', name: 'Light Ball', category: 'Pokémon-specific items', description: "If held by a Pikachu, its Attack and Sp. Atk are doubled." },
  { id: 'lustrous-globe', name: 'Lustrous Globe', category: 'Pokémon-specific items', description: "If held by a Palkia, its Water- and Dragon-type attacks have 1.2x power." },
  { id: 'lustrous-orb', name: 'Lustrous Orb', category: 'Pokémon-specific items', description: "If held by a Palkia, its Water- and Dragon-type attacks have 1.2x power." },
  { id: 'rusted-shield', name: 'Rusted Shield', category: 'Pokémon-specific items', description: 'If held by a Zamazenta, this item changes its forme to Crowned Shield.' },
  { id: 'rusted-sword', name: 'Rusted Sword', category: 'Pokémon-specific items', description: 'If held by a Zacian, this item changes its forme to Crowned Sword.' },
  { id: 'soul-dew', name: 'Soul Dew', category: 'Pokémon-specific items', description: "If held by a Latias/Latios, its Dragon- and Psychic-type moves have 1.2x power." },
  { id: 'wellspring-mask', name: 'Wellspring Mask', category: 'Pokémon-specific items', description: 'Ogerpon-Wellspring: 1.2x power attacks; Terastallize to gain Embody Aspect.' },
  { id: 'aspear-berry', name: 'Aspear Berry', category: 'Usually useless items', description: 'Holder is cured if it is frozen. Single use.' },
  { id: 'big-root', name: 'Big Root', category: 'Usually useless items', description: 'Holder gains 1.3x HP from draining/Aqua Ring/Ingrain/Leech Seed/Strength Sap.' },
  { id: 'binding-band', name: 'Binding Band', category: 'Usually useless items', description: 'Holder\'s partial-trapping moves deal 1/6 max HP per turn instead of 1/8.' },
  { id: 'cheri-berry', name: 'Cheri Berry', category: 'Usually useless items', description: 'Holder cures itself if it is paralyzed. Single use.' },
  { id: 'destiny-knot', name: 'Destiny Knot', category: 'Usually useless items', description: 'If holder becomes infatuated, the other Pokemon also becomes infatuated.' },
  { id: 'enigma-berry', name: 'Enigma Berry', category: 'Usually useless items', description: 'Restores 1/4 max HP after holder is hit by a supereffective move. Single use.' },
  { id: 'float-stone', name: 'Float Stone', category: 'Usually useless items', description: "Holder's weight is halved." },
  { id: 'focus-band', name: 'Focus Band', category: 'Usually useless items', description: 'Holder has a 10% chance to survive an attack that would KO it with 1 HP.' },
  { id: 'iron-ball', name: 'Iron Ball', category: 'Usually useless items', description: 'Holder is grounded, Speed halved. If Flying type, takes neutral Ground damage.' },
  { id: 'jaboca-berry', name: 'Jaboca Berry', category: 'Usually useless items', description: 'If holder is hit by a physical move, attacker loses 1/8 of its max HP. Single use.' },
  { id: 'oran-berry', name: 'Oran Berry', category: 'Usually useless items', description: 'Restores 10 HP when at 1/2 max HP or less. Single use.' },
  { id: 'pecha-berry', name: 'Pecha Berry', category: 'Usually useless items', description: 'Holder is cured if it is poisoned. Single use.' },
  { id: 'persim-berry', name: 'Persim Berry', category: 'Usually useless items', description: 'Holder is cured if it is confused. Single use.' },
  { id: 'power-anklet', name: 'Power Anklet', category: 'Usually useless items', description: "Holder's Speed is halved. The Klutz Ability does not ignore this effect." },
  { id: 'power-band', name: 'Power Band', category: 'Usually useless items', description: "Holder's Speed is halved. The Klutz Ability does not ignore this effect." },
  { id: 'power-belt', name: 'Power Belt', category: 'Usually useless items', description: "Holder's Speed is halved. The Klutz Ability does not ignore this effect." },
  { id: 'power-bracer', name: 'Power Bracer', category: 'Usually useless items', description: "Holder's Speed is halved. The Klutz Ability does not ignore this effect." },
  { id: 'power-lens', name: 'Power Lens', category: 'Usually useless items', description: "Holder's Speed is halved. The Klutz Ability does not ignore this effect." },
  { id: 'power-weight', name: 'Power Weight', category: 'Usually useless items', description: "Holder's Speed is halved. The Klutz Ability does not ignore this effect." },
  { id: 'rawst-berry', name: 'Rawst Berry', category: 'Usually useless items', description: 'Holder is cured if it is burned. Single use.' },
  { id: 'ring-target', name: 'Ring Target', category: 'Usually useless items', description: "The holder's type immunities granted solely by its typing are negated." },
  { id: 'rowap-berry', name: 'Rowap Berry', category: 'Usually useless items', description: 'If holder is hit by a special move, attacker loses 1/8 of its max HP. Single use.' },
  { id: 'auspicious-armor', name: 'Auspicious Armor', category: 'Useless items', description: 'Evolves Charcadet into Armarouge when used.' },
  { id: 'beast-ball', name: 'Beast Ball', category: 'Useless items', description: 'A special Poke Ball designed to catch Ultra Beasts.' },
  { id: 'berry-sweet', name: 'Berry Sweet', category: 'Useless items', description: 'Evolves Milcery into Alcremie when held and spun around.' },
  { id: 'big-nugget', name: 'Big Nugget', category: 'Useless items', description: 'A big nugget of pure gold that gives off a lustrous gleam.' },
  { id: 'bottle-cap', name: 'Bottle Cap', category: 'Useless items', description: "Used for Hyper Training. One of a Pokemon's stats is calculated with an IV of 31." },
  { id: 'chipped-pot', name: 'Chipped Pot', category: 'Useless items', description: 'Evolves Sinistea-Antique into Polteageist-Antique when used.' },
  { id: 'clover-sweet', name: 'Clover Sweet', category: 'Useless items', description: 'Evolves Milcery into Alcremie when held and spun around.' },
  { id: 'cracked-pot', name: 'Cracked Pot', category: 'Useless items', description: 'Evolves Sinistea into Polteageist when used.' },
  { id: 'dawn-stone', name: 'Dawn Stone', category: 'Useless items', description: 'Evolves certain species of Pokemon when used.' },
  { id: 'dive-ball', name: 'Dive Ball', category: 'Useless items', description: 'A Poke Ball that works especially well on Pokemon that live underwater.' },
  { id: 'dragon-scale', name: 'Dragon Scale', category: 'Useless items', description: 'Evolves Seadra into Kingdra when traded.' },
  { id: 'dream-ball', name: 'Dream Ball', category: 'Useless items', description: "A Poke Ball that makes it easier to catch wild Pokémon while they're asleep." },
  { id: 'dubious-disc', name: 'Dubious Disc', category: 'Useless items', description: 'Evolves Porygon2 into Porygon-Z when traded.' },
  { id: 'dusk-ball', name: 'Dusk Ball', category: 'Useless items', description: 'A Poke Ball that makes it easier to catch wild Pokemon at night or in caves.' },
  { id: 'dusk-stone', name: 'Dusk Stone', category: 'Useless items', description: 'Evolves certain species of Pokemon when used.' },
  { id: 'electirizer', name: 'Electirizer', category: 'Useless items', description: 'Evolves Electabuzz into Electivire when traded.' },
  { id: 'fast-ball', name: 'Fast Ball', category: 'Useless items', description: 'A Poke Ball that makes it easier to catch Pokemon which are quick to run away.' },
  { id: 'fire-stone', name: 'Fire Stone', category: 'Useless items', description: 'Evolves certain species of Pokemon when used.' },
  { id: 'flower-sweet', name: 'Flower Sweet', category: 'Useless items', description: 'Evolves Milcery into Alcremie when held and spun around.' },
  { id: 'friend-ball', name: 'Friend Ball', category: 'Useless items', description: 'A Poke Ball that makes caught Pokemon more friendly.' },
  { id: 'galarica-cuff', name: 'Galarica Cuff', category: 'Useless items', description: 'Evolves Galarian Slowpoke into Galarian Slowbro when used.' },
  { id: 'galarica-wreath', name: 'Galarica Wreath', category: 'Useless items', description: 'Evolves Galarian Slowpoke into Galarian Slowking when used.' },
  { id: 'gold-bottle-cap', name: 'Gold Bottle Cap', category: 'Useless items', description: "Used for Hyper Training. All of a Pokemon's stats are calculated with an IV of 31." },
  { id: 'great-ball', name: 'Great Ball', category: 'Useless items', description: 'A high-performance Ball that provides a higher catch rate than a Poke Ball.' },
  { id: 'heal-ball', name: 'Heal Ball', category: 'Useless items', description: "A remedial Poke Ball that restores the caught Pokemon's HP and status problem." },
  { id: 'heavy-ball', name: 'Heavy Ball', category: 'Useless items', description: 'A Poke Ball for catching very heavy Pokemon.' },
  { id: 'hondew-berry', name: 'Hondew Berry', category: 'Useless items', description: 'Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.' },
  { id: 'ice-stone', name: 'Ice Stone', category: 'Useless items', description: 'Evolves certain species of Pokemon when used.' },
  { id: 'leaf-stone', name: 'Leaf Stone', category: 'Useless items', description: 'Evolves certain species of Pokemon when used.' },
  { id: 'level-ball', name: 'Level Ball', category: 'Useless items', description: 'A Poke Ball for catching Pokemon that are a lower level than your own.' },
  { id: 'love-ball', name: 'Love Ball', category: 'Useless items', description: 'Poke Ball for catching Pokemon that are the opposite gender of your Pokemon.' },
  { id: 'love-sweet', name: 'Love Sweet', category: 'Useless items', description: 'Evolves Milcery into Alcremie when held and spun around.' },
  { id: 'lure-ball', name: 'Lure Ball', category: 'Useless items', description: 'A Poke Ball for catching Pokemon hooked by a Rod when fishing.' },
  { id: 'luxury-ball', name: 'Luxury Ball', category: 'Useless items', description: 'A comfortable Poke Ball that makes a caught wild Pokemon quickly grow friendly.' },
  { id: 'magmarizer', name: 'Magmarizer', category: 'Useless items', description: 'Evolves Magmar into Magmortar when traded.' },
  { id: 'malicious-armor', name: 'Malicious Armor', category: 'Useless items', description: 'Evolves Charcadet into Ceruledge when used.' },
  { id: 'master-ball', name: 'Master Ball', category: 'Useless items', description: 'The best Ball with the ultimate performance. It will catch any wild Pokemon.' },
  { id: 'masterpiece-teacup', name: 'Masterpiece Teacup', category: 'Useless items', description: 'Evolves Poltchageist-Artisan into Sinistcha-Masterpiece when used.' },
  { id: 'metal-alloy', name: 'Metal Alloy', category: 'Useless items', description: 'Evolves Duraludon into Archaludon when used.' },
  { id: 'moon-ball', name: 'Moon Ball', category: 'Useless items', description: 'A Poke Ball for catching Pokemon that evolve using the Moon Stone.' },
  { id: 'moon-stone', name: 'Moon Stone', category: 'Useless items', description: 'Evolves certain species of Pokemon when used.' },
  { id: 'nest-ball', name: 'Nest Ball', category: 'Useless items', description: 'A Poke Ball that works especially well on weaker Pokemon in the wild.' },
  { id: 'net-ball', name: 'Net Ball', category: 'Useless items', description: 'A Poke Ball that works especially well on Water- and Bug-type Pokemon.' },
  { id: 'oval-stone', name: 'Oval Stone', category: 'Useless items', description: 'Evolves Happiny into Chansey when held and leveled up during the day.' },
  { id: 'poke-ball', name: 'Poke Ball', category: 'Useless items', description: 'A device for catching wild Pokemon. It is designed as a capsule system.' },
  { id: 'pomeg-berry', name: 'Pomeg Berry', category: 'Useless items', description: 'Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.' },
  { id: 'premier-ball', name: 'Premier Ball', category: 'Useless items', description: 'A rare Poke Ball that has been crafted to commemorate an event.' },
  { id: 'prism-scale', name: 'Prism Scale', category: 'Useless items', description: 'Evolves Feebas into Milotic when traded.' },
  { id: 'protector', name: 'Protector', category: 'Useless items', description: 'Evolves Rhydon into Rhyperior when traded.' },
  { id: 'qualot-berry', name: 'Qualot Berry', category: 'Useless items', description: 'Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.' },
  { id: 'quick-ball', name: 'Quick Ball', category: 'Useless items', description: 'A Poke Ball that provides a better catch rate at the start of a wild encounter.' },
  { id: 'rare-bone', name: 'Rare Bone', category: 'Useless items', description: 'No competitive use other than when used with Fling.' },
  { id: 'reaper-cloth', name: 'Reaper Cloth', category: 'Useless items', description: 'Evolves Dusclops into Dusknoir when traded.' },
  { id: 'repeat-ball', name: 'Repeat Ball', category: 'Useless items', description: 'A Poke Ball that works well on Pokemon species that were previously caught.' },
  { id: 'ribbon-sweet', name: 'Ribbon Sweet', category: 'Useless items', description: 'Evolves Milcery into Alcremie when held and spun around.' },
  { id: 'safari-ball', name: 'Safari Ball', category: 'Useless items', description: 'A special Poke Ball that is used only in the Safari Zone and Great Marsh.' },
  { id: 'shiny-stone', name: 'Shiny Stone', category: 'Useless items', description: 'Evolves certain species of Pokemon when used.' },
  { id: 'sport-ball', name: 'Sport Ball', category: 'Useless items', description: 'A special Poke Ball for the Bug-Catching Contest.' },
  { id: 'star-sweet', name: 'Star Sweet', category: 'Useless items', description: 'Evolves Milcery into Alcremie when held and spun around.' },
  { id: 'strawberry-sweet', name: 'Strawberry Sweet', category: 'Useless items', description: 'Evolves Milcery into Alcremie when held and spun around.' },
  { id: 'sun-stone', name: 'Sun Stone', category: 'Useless items', description: 'Evolves certain species of Pokemon when used.' },
  { id: 'sweet-apple', name: 'Sweet Apple', category: 'Useless items', description: 'Evolves Applin into Appletun when used.' },
  { id: 'syrupy-apple', name: 'Syrupy Apple', category: 'Useless items', description: 'Evolves Applin into Dipplin when used.' },
  { id: 'tamato-berry', name: 'Tamato Berry', category: 'Useless items', description: 'Cannot be eaten by the holder. No effect when eaten with Bug Bite or Pluck.' },
  { id: 'tart-apple', name: 'Tart Apple', category: 'Useless items', description: 'Evolves Applin into Flapple when used.' },
  { id: 'thunder-stone', name: 'Thunder Stone', category: 'Useless items', description: 'Evolves certain species of Pokemon when used.' },
  { id: 'timer-ball', name: 'Timer Ball', category: 'Useless items', description: 'A Poke Ball that becomes better the more turns there are in a battle.' },
  { id: 'ultra-ball', name: 'Ultra Ball', category: 'Useless items', description: 'An ultra-performance Ball that provides a higher catch rate than a Great Ball.' },
  { id: 'unremarkable-teacup', name: 'Unremarkable Teacup', category: 'Useless items', description: 'Evolves Poltchageist into Sinistcha when used.' },
  { id: 'up-grade', name: 'Up-Grade', category: 'Useless items', description: 'Evolves Porygon into Porygon2 when traded.' },
  { id: 'water-stone', name: 'Water Stone', category: 'Useless items', description: 'Evolves certain species of Pokemon when used.' },
]
/**
 * Devuelve la URL del sprite de un objeto basado en su ID.
 * @param {string} itemId - El ID del objeto (ej. 'life-orb').
 * @returns {string} - La URL completa del sprite.
 */
export function getItemSpriteUrl(itemId) {
  if (!itemId) return ''; 
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/${itemId.toLowerCase().replace(/ /g, '-')}.png`;
}