// src/utils/moves.js


export const moveData = {
  // Common Moves
  "agility": { name: "Agility", type: "psychic", category: "status", power: null, accuracy: null, pp: 30, description: "Sharply raises the user's Speed.", group: "Common Moves" },
  "blizzard": { name: "Blizzard", type: "ice", category: "special", power: 110, accuracy: 70, pp: 5, description: "10% freeze chance. Can't miss in hail.", group: "Common Moves" },
  "body-slam": { name: "Body Slam", type: "normal", category: "physical", power: 85, accuracy: 100, pp: 15, description: "30% chance to paralyze the target.", group: "Common Moves" },
  "calm-mind": { name: "Calm Mind", type: "psychic", category: "status", power: null, accuracy: null, pp: 20, description: "Raises the user's Sp. Atk and Sp. Def by 1.", group: "Common Moves" },
  "close-combat": { name: "Close Combat", type: "fighting", category: "physical", power: 120, accuracy: 100, pp: 5, description: "Lowers the user's Defense and Sp. Def by 1.", group: "Common Moves" },
  "dark-pulse": { name: "Dark Pulse", type: "dark", category: "special", power: 80, accuracy: 100, pp: 15, description: "20% chance to make the target flinch.", group: "Common Moves" },
  "dazzling-gleam": { name: "Dazzling Gleam", type: "fairy", category: "special", power: 80, accuracy: 100, pp: 10, description: "Hits all adjacent foes.", group: "Common Moves" },
  "draco-meteor": { name: "Draco Meteor", type: "dragon", category: "special", power: 130, accuracy: 90, pp: 5, description: "Lowers the user's Sp. Atk by 2.", group: "Common Moves" },
  "dragon-claw": { name: "Dragon Claw", type: "dragon", category: "physical", power: 80, accuracy: 100, pp: 15, description: "No additional effect.", group: "Common Moves" },
  "earthquake": { name: "Earthquake", type: "ground", category: "physical", power: 100, accuracy: 100, pp: 10, description: "Hits all adjacent Pokémon except Flying-types.", group: "Common Moves" },
  "energy-ball": { name: "Energy Ball", type: "grass", category: "special", power: 90, accuracy: 100, pp: 10, description: "10% chance to lower the target's Sp. Def by 1.", group: "Common Moves" },
  "fire-blast": { name: "Fire Blast", type: "fire", category: "special", power: 110, accuracy: 85, pp: 5, description: "10% chance to burn the target.", group: "Common Moves" },
  "flamethrower": { name: "Flamethrower", type: "fire", category: "special", power: 90, accuracy: 100, pp: 15, description: "10% chance to burn the target.", group: "Common Moves" },
  "flare-blitz": { name: "Flare Blitz", type: "fire", category: "physical", power: 120, accuracy: 100, pp: 15, description: "User takes 1/3 recoil damage. 10% burn chance.", group: "Common Moves" },
  "heat-wave": { name: "Heat Wave", type: "fire", category: "special", power: 95, accuracy: 90, pp: 10, description: "10% chance to burn the foe(s).", group: "Common Moves" },
  "hydro-pump": { name: "Hydro Pump", type: "water", category: "special", power: 110, accuracy: 80, pp: 5, description: "High power, lower accuracy.", group: "Common Moves" },
  "hyper-beam": { name: "Hyper Beam", type: "normal", category: "special", power: 150, accuracy: 90, pp: 5, description: "User cannot move next turn.", group: "Common Moves" },
  "ice-beam": { name: "Ice Beam", type: "ice", category: "special", power: 90, accuracy: 100, pp: 10, description: "10% chance to freeze the target.", group: "Common Moves" },
  "play-rough": { name: "Play Rough", type: "fairy", category: "physical", power: 90, accuracy: 90, pp: 10, description: "10% chance to lower the target's Attack by 1.", group: "Common Moves" },
  "protect": { name: "Protect", type: "normal", category: "status", power: null, accuracy: null, pp: 10, description: "Protects from most moves.", group: "Common Moves" },
  "psychic": { name: "Psychic", type: "psychic", category: "special", power: 90, accuracy: 100, pp: 10, description: "10% chance to lower the target's Sp. Def by 1.", group: "Common Moves" },
  "scald": { name: "Scald", type: "water", category: "special", power: 80, accuracy: 100, pp: 15, description: "30% chance to burn the target.", group: "Common Moves" },
  "shadow-ball": { name: "Shadow Ball", type: "ghost", category: "special", power: 80, accuracy: 100, pp: 15, description: "20% chance to lower the target's Sp. Def by 1.", group: "Common Moves" },
  "sludge-bomb": { name: "Sludge Bomb", type: "poison", category: "special", power: 90, accuracy: 100, pp: 10, description: "30% chance to poison the target.", group: "Common Moves" },
  "surf": { name: "Surf", type: "water", category: "special", power: 90, accuracy: 100, pp: 15, description: "Hits all adjacent Pokémon.", group: "Common Moves" },
  "swords-dance": { name: "Swords Dance", type: "normal", category: "status", power: null, accuracy: null, pp: 20, description: "Raises the user's Attack by 2.", group: "Common Moves" },
  "tera-blast": { name: "Tera Blast", type: "normal", category: "special", power: 80, accuracy: 100, pp: 10, description: "If Terastallized, becomes user's Tera Type.", group: "Common Moves" },
  "thunder-wave": { name: "Thunder Wave", type: "electric", category: "status", power: null, accuracy: 90, pp: 20, description: "Paralyzes the target.", group: "Common Moves" },
  "thunderbolt": { name: "Thunderbolt", type: "electric", category: "special", power: 90, accuracy: 100, pp: 15, description: "10% chance to paralyze the target.", group: "Common Moves" },
  "u-turn": { name: "U-turn", type: "bug", category: "physical", power: 70, accuracy: 100, pp: 20, description: "User switches out after attacking.", group: "Common Moves" },
  "will-o-wisp": { name: "Will-O-Wisp", type: "fire", category: "status", power: null, accuracy: 85, pp: 15, description: "Burns the target.", group: "Common Moves" },
  
  // Other Moves
  "alluring-voice": { name: "Alluring Voice", type: "fairy", category: "special", power: 80, accuracy: null, pp: 10, description: "Never misses. If target's stats were raised this turn, it becomes confused.", group: "Other Moves" },
  "chilling-water": { name: "Chilling Water", type: "water", category: "special", power: 50, accuracy: 100, pp: 20, description: "Lowers the target's Attack by 1.", group: "Other Moves" },
  "clear-smog": { name: "Clear Smog", type: "poison", category: "special", power: 50, accuracy: null, pp: 15, description: "Resets all of the target's stat stages to 0.", group: "Other Moves" },
  "court-change": { name: "Court Change", type: "normal", category: "status", power: null, accuracy: 100, pp: 10, description: "Swaps the field effects on both sides.", group: "Other Moves" },
  "curse": { name: "Curse", type: "ghost", category: "status", power: null, accuracy: null, pp: 10, description: "Curses if Ghost, else -1 Spe, +1 Atk, +1 Def.", group: "Other Moves" },
  "disable": { name: "Disable", type: "normal", category: "status", power: null, accuracy: 100, pp: 20, description: "For 4 turns, disables the target's last move used.", group: "Other Moves" },
  "double-edge": { name: "Double-Edge", type: "normal", category: "physical", power: 120, accuracy: 100, pp: 15, description: "User receives 33% recoil damage.", group: "Other Moves" },
  "facade": { name: "Facade", type: "normal", category: "physical", power: 70, accuracy: 100, pp: 20, description: "Power doubles if the user is burned, paralyzed, or poisoned.", group: "Other Moves" },
  "flame-charge": { name: "Flame Charge", type: "fire", category: "physical", power: 50, accuracy: 100, pp: 20, description: "Raises the user's Speed by 1.", group: "Other Moves" },
  "flash-cannon": { name: "Flash Cannon", type: "steel", category: "special", power: 80, accuracy: 100, pp: 10, description: "10% chance to lower the target's Sp. Def by 1.", group: "Other Moves" },
  "flip-turn": { name: "Flip Turn", type: "water", category: "physical", power: 60, accuracy: 100, pp: 20, description: "User switches out after attacking.", group: "Other Moves" },
  "giga-drain": { name: "Giga Drain", type: "grass", category: "special", power: 75, accuracy: 100, pp: 10, description: "User recovers 50% of the damage dealt.", group: "Other Moves" },
  "grass-knot": { name: "Grass Knot", type: "grass", category: "special", power: null, accuracy: 100, pp: 20, description: "More power the heavier the target.", group: "Other Moves" },
  "hone-claws": { name: "Hone Claws", type: "dark", category: "status", power: null, accuracy: null, pp: 15, description: "Raises the user's Attack and accuracy by 1.", group: "Other Moves" },
  "iron-defense": { name: "Iron Defense", type: "steel", category: "status", power: null, accuracy: null, pp: 15, description: "Sharply raises the user's Defense.", group: "Other Moves" },
  "knock-off": { name: "Knock Off", type: "dark", category: "physical", power: 65, accuracy: 100, pp: 20, description: "1.5x damage if foe holds an item. Removes item.", group: "Other Moves" },
  "leaf-storm": { name: "Leaf Storm", type: "grass", category: "special", power: 130, accuracy: 90, pp: 5, description: "Lowers the user's Sp. Atk by 2.", group: "Other Moves" },
  "leech-life": { name: "Leech Life", type: "bug", category: "physical", power: 80, accuracy: 100, pp: 10, description: "User recovers 50% of the damage dealt.", group: "Other Moves" },
  "leech-seed": { name: "Leech Seed", type: "grass", category: "status", power: null, accuracy: 90, pp: 10, description: "1/8 of target's HP is restored to user every turn.", group: "Other Moves" },
  "light-screen": { name: "Light Screen", type: "psychic", category: "status", power: null, accuracy: null, pp: 30, description: "For 5 turns, special damage to allies is halved.", group: "Other Moves" },
  "lunge": { name: "Lunge", type: "bug", category: "physical", power: 80, accuracy: 100, pp: 15, description: "Lowers the target's Attack by 1.", group: "Other Moves" },
  "power-whip": { name: "Power Whip", type: "grass", category: "physical", power: 120, accuracy: 85, pp: 10, description: "No additional effect.", group: "Other Moves" },
  "rest": { name: "Rest", type: "psychic", category: "status", power: null, accuracy: null, pp: 10, description: "User sleeps 2 turns and restores HP and status.", group: "Other Moves" },
  "seed-bomb": { name: "Seed Bomb", type: "grass", category: "physical", power: 80, accuracy: 100, pp: 15, description: "No additional effect.", group: "Other Moves" },
  "sleep-talk": { name: "Sleep Talk", type: "normal", category: "status", power: null, accuracy: null, pp: 10, description: "User must be asleep. Uses another known move.", group: "Other Moves" },
  "substitute": { name: "Substitute", type: "normal", category: "status", power: null, accuracy: null, pp: 10, description: "User takes 1/4 its max HP to put in a substitute.", group: "Other Moves" },
  "synthesis": { name: "Synthesis", type: "grass", category: "status", power: null, accuracy: null, pp: 5, description: "Heals the user by a weather-dependent amount.", group: "Other Moves" },
  "toxic": { name: "Toxic", type: "poison", category: "status", power: null, accuracy: 90, pp: 10, description: "Badly poisons the target. Poison types can't miss.", group: "Other Moves" },
  "trailblaze": { name: "Trailblaze", type: "grass", category: "physical", power: 50, accuracy: 100, pp: 20, description: "Raises the user's Speed by 1.", group: "Other Moves" },
  "weather-ball": { name: "Weather Ball", type: "normal", category: "special", power: 50, accuracy: 100, pp: 10, description: "Power doubles and type varies in each weather.", group: "Other Moves" },
  "lava-plume": { name: "Lava Plume", type: "fire", category: "special", power: 80, accuracy: 100, pp: 15, description: "30% chance to burn adjacent Pokémon.", group: "Other Moves" },
  "night-shade": { name: "Night Shade", type: "ghost", category: "special", power: null, accuracy: 100, pp: 15, description: "Does damage equal to the user's level.", group: "Other Moves" },
  
  // Usually useless moves
  "acid-spray": { name: "Acid Spray", type: "poison", category: "special", power: 40, accuracy: 100, pp: 20, description: "Harshly lowers target's Sp. Def.", group: "Usually Useless Moves" },
  "bullet-seed": { name: "Bullet Seed", type: "grass", category: "physical", power: 25, accuracy: 100, pp: 30, description: "Hits 2-5 times in one turn.", group: "Usually Useless Moves" },
  "charm": { name: "Charm", type: "fairy", category: "status", power: null, accuracy: 100, pp: 20, description: "Harshly lowers target's Attack.", group: "Usually Useless Moves" },
  "endure": { name: "Endure", type: "normal", category: "status", power: null, accuracy: null, pp: 10, description: "User survives attacks with 1 HP for 1 turn.", group: "Usually Useless Moves" },
  "false-swipe": { name: "False Swipe", type: "normal", category: "physical", power: 40, accuracy: 100, pp: 40, description: "Always leaves the target with at least 1 HP.", group: "Usually Useless Moves" },
};